# Generated by Django 4.2 on 2024-10-29 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stock_Data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sma_50', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sma_200', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rsi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('macd', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('signal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='Stock_Data.stock')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
