"""
Django settings for PORTOFOLIO project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&@8z*^j($rdi5a6+^37n7oygk%2y3%th7wji+z$)pr2=!jwy3h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']

# Application definition

INSTALLED_APPS = [
    # 'grappelli',            # Tambahkan di paling atas
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Stock_Data',
    'Dashboard',
    'Watchlist',
    'Alerts',
    'News', 
    'django.contrib.humanize',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'PORTOFOLIO.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PORTOFOLIO.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Pastikan ini ada
        'NAME': os.environ.get('DB_NAME', 'postgres'),  # Nama database
        'USER': os.environ.get('DB_USER', 'postgres'),  # Nama pengguna
        'PASSWORD': os.environ.get('DB_PASSWORD', '12345678'),  # Kata sandi
        'HOST': 'postgres_db',  # Service name in docker-compose
        'PORT': '5432',  # Port database
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend',
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend',

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', #DEFAULT BACKEND
    'allauth.account.auth_backends.AuthenticationBackend', # GOOGLE
]

# LOGIN OAUTH
SOCIALACCOUNT_PROVIDERS = {
    'github':{
        'APP':{
            'client_id': 'Ov23liQTmCiVWBhxZDhc',
            'secret': '2c93bb0aa1117ce517e233c28a2483a229468686',
        }
    },
    'discord':{
        'APP':{
            'client_id': '1329290560640647288',
            'secret': 'iEaUNvRltP9vMZN_tkhLt1Ro4aHSycvl',
        }
    }
}

SOCIALACCOUNT_LOGIN_ON_GET = False

LOGIN_URL = '/login/?'  # Ganti dengan URL login Anda
LOGOUT_URL = '/Home'
LOGIN_REDIRECT_URL = '/dashboard/'  # Ganti dengan URL dashboard Anda
ACCOUNT_LOGOUT_REDIRECT_URL = 'login'

SITE_ID = 2

MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Pengaturan untuk file media
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")